apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: d1qhw6qhb-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-643fb0cca6.cpmk.p3.openshiftapps.com/rhtap/rhtap-qe:14284041b9d2ff3dc5b18ddcc269c30178841274@sha256:38bb112704e3c10926949dd6fb69580dfe11cc011352f44e115da6ebcfc31b65
          name: container-image
